### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by krrish94** [gradsim/gradsim#1]
Please subscribe to this issue (click the "Subscribe" button on the right) if you'd like to be notified of the code release.

**Comment by zc-alexfan** [comment]
Is there an estimated period the code will be released?

**Comment by ANABUR920** [comment]
Awesome work! I cannot wait to see it!

**Comment by korzen** [comment]
Hi, any news on the code release?

Cheers

**Comment by krrish94** [comment]
The code is now publicly available - closing this topic.

Please feel free to create newer topics for any specific issues that arise over the next few weeks and we would be happy to assist.
